name: "sonar_cloud_scan_github_actions"
on:
  workflow_dispatch:

jobs:
  DemoSonarCloudScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Aquí se hace el cambio al directorio donde está el pom.xml, si está en una subcarpeta
      - name: Build with Maven
        run: |
          cd path/to/your/project  # Cambia 'path/to/your/project' por la ruta real donde está el pom.xml
          mvn clean install

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKENG }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=gilsonorlando
            -Dsonar.projectKey=gilsonOrlando_tableroB
            -Dsonar.java.binaries=target/classes
            -Dsonar.java.coverage.reportPaths=coverage.xml
